# Generated by Django 2.2.16 on 2022-08-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Пользователь', 'User'), ('Модератор', 'Moderator'), ('Администратор', 'Admin')], default='Пользователь', max_length=50, verbose_name='Роль пользователя'),
        ),
    ]
