# Generated by Django 2.2.16 on 2022-08-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220809_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Пользователь', 'user'), ('Модератор', 'moderator'), ('Администратор', 'admin')], default='Пользователь', max_length=50, verbose_name='Роль пользователя'),
        ),
    ]
